use_frameworks!

platform :ios, '10.0'

target 'Maroc_Example' do
  pod 'Maroc', :path => '../'

  target 'Maroc_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
